# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `sin_lru_redux` gem.
# Please instead update this file by running `bin/tapioca gem sin_lru_redux`.


# source://sin_lru_redux//lib/lru_redux/version.rb#3
module LruRedux; end

# source://sin_lru_redux//lib/lru_redux/cache.rb#4
class LruRedux::Cache
  # @return [Cache] a new instance of Cache
  #
  # source://sin_lru_redux//lib/lru_redux/cache.rb#7
  def initialize(*args); end

  # source://sin_lru_redux//lib/lru_redux/cache.rb#63
  def [](key); end

  # source://sin_lru_redux//lib/lru_redux/cache.rb#71
  def []=(key, val); end

  # source://sin_lru_redux//lib/lru_redux/cache.rb#99
  def clear; end

  # source://sin_lru_redux//lib/lru_redux/cache.rb#103
  def count; end

  # source://sin_lru_redux//lib/lru_redux/cache.rb#89
  def delete(key); end

  # source://sin_lru_redux//lib/lru_redux/cache.rb#75
  def each(&block); end

  # Used further up the chain, non thread safe each
  #
  # source://sin_lru_redux//lib/lru_redux/cache.rb#79
  def each_unsafe(&block); end

  # source://sin_lru_redux//lib/lru_redux/cache.rb#92
  def evict(key); end

  # source://sin_lru_redux//lib/lru_redux/cache.rb#52
  def fetch(key); end

  # source://sin_lru_redux//lib/lru_redux/cache.rb#39
  def getset(key); end

  # @return [Boolean]
  #
  # source://sin_lru_redux//lib/lru_redux/cache.rb#97
  def has_key?(key); end

  # Returns the value of attribute ignore_nil.
  #
  # source://sin_lru_redux//lib/lru_redux/cache.rb#5
  def ignore_nil; end

  # source://sin_lru_redux//lib/lru_redux/cache.rb#32
  def ignore_nil=(new_ignore_nil); end

  # @return [Boolean]
  #
  # source://sin_lru_redux//lib/lru_redux/cache.rb#94
  def key?(key); end

  # source://sin_lru_redux//lib/lru_redux/cache.rb#106
  def length; end

  # Returns the value of attribute max_size.
  #
  # source://sin_lru_redux//lib/lru_redux/cache.rb#5
  def max_size; end

  # source://sin_lru_redux//lib/lru_redux/cache.rb#21
  def max_size=(new_max_size); end

  # source://sin_lru_redux//lib/lru_redux/cache.rb#107
  def size; end

  # source://sin_lru_redux//lib/lru_redux/cache.rb#81
  def to_a; end

  # source://sin_lru_redux//lib/lru_redux/cache.rb#28
  def ttl=(_); end

  # source://sin_lru_redux//lib/lru_redux/cache.rb#85
  def values; end

  private

  # source://sin_lru_redux//lib/lru_redux/cache.rb#140
  def evict_excess; end

  # source://sin_lru_redux//lib/lru_redux/cache.rb#145
  def evict_nil; end

  # source://sin_lru_redux//lib/lru_redux/cache.rb#158
  def store_item(key, val); end

  # For cache validation only, ensure all is valid
  #
  # @return [Boolean]
  #
  # source://sin_lru_redux//lib/lru_redux/cache.rb#112
  def valid?; end

  # @raise [ArgumentError]
  #
  # source://sin_lru_redux//lib/lru_redux/cache.rb#131
  def validate_ignore_nil!(ignore_nil); end

  # @raise [ArgumentError]
  #
  # source://sin_lru_redux//lib/lru_redux/cache.rb#116
  def validate_max_size!(max_size); end
end

# source://sin_lru_redux//lib/lru_redux/ttl/cache.rb#4
module LruRedux::TTL; end

# source://sin_lru_redux//lib/lru_redux/ttl/cache.rb#5
class LruRedux::TTL::Cache
  # @return [Cache] a new instance of Cache
  #
  # source://sin_lru_redux//lib/lru_redux/ttl/cache.rb#8
  def initialize(*args); end

  # source://sin_lru_redux//lib/lru_redux/ttl/cache.rb#80
  def [](key); end

  # source://sin_lru_redux//lib/lru_redux/ttl/cache.rb#92
  def []=(key, val); end

  # source://sin_lru_redux//lib/lru_redux/ttl/cache.rb#132
  def clear; end

  # source://sin_lru_redux//lib/lru_redux/ttl/cache.rb#137
  def count; end

  # source://sin_lru_redux//lib/lru_redux/ttl/cache.rb#117
  def delete(key); end

  # source://sin_lru_redux//lib/lru_redux/ttl/cache.rb#98
  def each(&block); end

  # source://sin_lru_redux//lib/lru_redux/ttl/cache.rb#103
  def each_unsafe(&block); end

  # source://sin_lru_redux//lib/lru_redux/ttl/cache.rb#123
  def evict(key); end

  # source://sin_lru_redux//lib/lru_redux/ttl/cache.rb#143
  def expire; end

  # source://sin_lru_redux//lib/lru_redux/ttl/cache.rb#65
  def fetch(key); end

  # source://sin_lru_redux//lib/lru_redux/ttl/cache.rb#48
  def getset(key); end

  # @return [Boolean]
  #
  # source://sin_lru_redux//lib/lru_redux/ttl/cache.rb#130
  def has_key?(key); end

  # Returns the value of attribute ignore_nil.
  #
  # source://sin_lru_redux//lib/lru_redux/ttl/cache.rb#6
  def ignore_nil; end

  # source://sin_lru_redux//lib/lru_redux/ttl/cache.rb#41
  def ignore_nil=(new_ignore_nil); end

  # @return [Boolean]
  #
  # source://sin_lru_redux//lib/lru_redux/ttl/cache.rb#125
  def key?(key); end

  # source://sin_lru_redux//lib/lru_redux/ttl/cache.rb#140
  def length; end

  # Returns the value of attribute max_size.
  #
  # source://sin_lru_redux//lib/lru_redux/ttl/cache.rb#6
  def max_size; end

  # source://sin_lru_redux//lib/lru_redux/ttl/cache.rb#26
  def max_size=(new_max_size); end

  # source://sin_lru_redux//lib/lru_redux/ttl/cache.rb#141
  def size; end

  # source://sin_lru_redux//lib/lru_redux/ttl/cache.rb#105
  def to_a; end

  # Returns the value of attribute ttl.
  #
  # source://sin_lru_redux//lib/lru_redux/ttl/cache.rb#6
  def ttl; end

  # source://sin_lru_redux//lib/lru_redux/ttl/cache.rb#34
  def ttl=(new_ttl); end

  # source://sin_lru_redux//lib/lru_redux/ttl/cache.rb#111
  def values; end

  private

  # source://sin_lru_redux//lib/lru_redux/ttl/cache.rb#192
  def evict_excess; end

  # source://sin_lru_redux//lib/lru_redux/ttl/cache.rb#199
  def evict_expired; end

  # source://sin_lru_redux//lib/lru_redux/ttl/cache.rb#211
  def evict_nil; end

  # source://sin_lru_redux//lib/lru_redux/ttl/cache.rb#224
  def store_item(key, value); end

  # For cache validation only, ensure all is valid
  #
  # @return [Boolean]
  #
  # source://sin_lru_redux//lib/lru_redux/ttl/cache.rb#150
  def valid?; end

  # @raise [ArgumentError]
  #
  # source://sin_lru_redux//lib/lru_redux/ttl/cache.rb#186
  def validate_ignore_nil!(ignore_nil); end

  # @raise [ArgumentError]
  #
  # source://sin_lru_redux//lib/lru_redux/ttl/cache.rb#154
  def validate_max_size!(max_size); end

  # @raise [ArgumentError]
  #
  # source://sin_lru_redux//lib/lru_redux/ttl/cache.rb#169
  def validate_ttl!(ttl); end
end

# source://sin_lru_redux//lib/lru_redux/ttl/thread_safe_cache.rb#5
class LruRedux::TTL::ThreadSafeCache < ::LruRedux::TTL::Cache
  include ::MonitorMixin
  include ::LruRedux::Util::SafeSync
end

# source://sin_lru_redux//lib/lru_redux/thread_safe_cache.rb#4
class LruRedux::ThreadSafeCache < ::LruRedux::Cache
  include ::MonitorMixin
  include ::LruRedux::Util::SafeSync
end

# source://sin_lru_redux//lib/lru_redux/util/safe_sync.rb#6
module LruRedux::Util; end

# source://sin_lru_redux//lib/lru_redux/util/safe_sync.rb#7
module LruRedux::Util::SafeSync
  include ::MonitorMixin

  # source://sin_lru_redux//lib/lru_redux/util/safe_sync.rb#10
  def initialize(*args); end

  # source://sin_lru_redux//lib/lru_redux/util/safe_sync.rb#44
  def [](key); end

  # source://sin_lru_redux//lib/lru_redux/util/safe_sync.rb#50
  def []=(key, value); end

  # source://sin_lru_redux//lib/lru_redux/util/safe_sync.rb#98
  def clear; end

  # source://sin_lru_redux//lib/lru_redux/util/safe_sync.rb#104
  def count; end

  # source://sin_lru_redux//lib/lru_redux/util/safe_sync.rb#74
  def delete(key); end

  # source://sin_lru_redux//lib/lru_redux/util/safe_sync.rb#56
  def each; end

  # source://sin_lru_redux//lib/lru_redux/util/safe_sync.rb#80
  def evict(key); end

  # source://sin_lru_redux//lib/lru_redux/util/safe_sync.rb#38
  def fetch(key); end

  # source://sin_lru_redux//lib/lru_redux/util/safe_sync.rb#32
  def getset(key); end

  # @return [Boolean]
  #
  # source://sin_lru_redux//lib/lru_redux/util/safe_sync.rb#92
  def has_key?(key); end

  # source://sin_lru_redux//lib/lru_redux/util/safe_sync.rb#26
  def ignore_nil=(ignore_nil); end

  # @return [Boolean]
  #
  # source://sin_lru_redux//lib/lru_redux/util/safe_sync.rb#86
  def key?(key); end

  # source://sin_lru_redux//lib/lru_redux/util/safe_sync.rb#14
  def max_size=(max_size); end

  # source://sin_lru_redux//lib/lru_redux/util/safe_sync.rb#62
  def to_a; end

  # source://sin_lru_redux//lib/lru_redux/util/safe_sync.rb#20
  def ttl=(ttl); end

  # source://sin_lru_redux//lib/lru_redux/util/safe_sync.rb#68
  def values; end

  private

  # @return [Boolean]
  #
  # source://sin_lru_redux//lib/lru_redux/util/safe_sync.rb#112
  def valid?; end
end

# source://sin_lru_redux//lib/lru_redux/version.rb#4
LruRedux::VERSION = T.let(T.unsafe(nil), String)
