# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `tailwindcss-rails` gem.
# Please instead update this file by running `bin/tapioca gem tailwindcss-rails`.


# source://tailwindcss-rails//lib/tailwindcss-rails.rb#1
module Tailwindcss; end

# source://tailwindcss-rails//lib/tailwindcss/commands.rb#4
module Tailwindcss::Commands
  class << self
    # source://tailwindcss-rails//lib/tailwindcss/commands.rb#31
    def command_env(verbose:); end

    # source://tailwindcss-rails//lib/tailwindcss/commands.rb#6
    def compile_command(debug: T.unsafe(nil), **kwargs); end

    # @return [Boolean]
    #
    # source://tailwindcss-rails//lib/tailwindcss/commands.rb#37
    def rails_css_compressor?; end

    # source://tailwindcss-rails//lib/tailwindcss/commands.rb#24
    def watch_command(always: T.unsafe(nil), **kwargs); end
  end
end

# source://tailwindcss-rails//lib/tailwindcss/engine.rb#4
class Tailwindcss::Engine < ::Rails::Engine; end

# source://tailwindcss-rails//lib/tailwindcss/engines.rb#2
module Tailwindcss::Engines
  class << self
    # source://tailwindcss-rails//lib/tailwindcss/engines.rb#4
    def bundle; end
  end
end

# source://tailwindcss-rails//lib/tailwindcss/version.rb#2
Tailwindcss::VERSION = T.let(T.unsafe(nil), String)
