# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `tailwind_merge` gem.
# Please instead update this file by running `bin/tapioca gem tailwind_merge`.


# source://tailwind_merge//lib/tailwind_merge/version.rb#3
module TailwindMerge; end

# source://tailwind_merge//lib/tailwind_merge/class_group_utils.rb#4
class TailwindMerge::ClassGroupUtils
  # @return [ClassGroupUtils] a new instance of ClassGroupUtils
  #
  # source://tailwind_merge//lib/tailwind_merge/class_group_utils.rb#11
  def initialize(config); end

  # source://tailwind_merge//lib/tailwind_merge/class_group_utils.rb#16
  def class_group_id(class_name); end

  # Returns the value of attribute class_map.
  #
  # source://tailwind_merge//lib/tailwind_merge/class_group_utils.rb#5
  def class_map; end

  # source://tailwind_merge//lib/tailwind_merge/class_group_utils.rb#50
  def get_conflicting_class_group_ids(class_group_id, has_postfix_modifier); end

  # source://tailwind_merge//lib/tailwind_merge/class_group_utils.rb#26
  def get_group_recursive(class_parts, class_part_object); end

  private

  # source://tailwind_merge//lib/tailwind_merge/class_group_utils.rb#60
  def create_class_map(config); end

  # @return [Boolean]
  #
  # source://tailwind_merge//lib/tailwind_merge/class_group_utils.rb#129
  def from_theme?(validator); end

  # source://tailwind_merge//lib/tailwind_merge/class_group_utils.rb#102
  def get_class_part(class_part_object, path); end

  # source://tailwind_merge//lib/tailwind_merge/class_group_utils.rb#119
  def get_group_id_for_arbitrary_property(class_name); end

  # source://tailwind_merge//lib/tailwind_merge/class_group_utils.rb#75
  def process_classes_recursively(class_group, class_part_object, class_group_id, theme); end
end

# source://tailwind_merge//lib/tailwind_merge/class_group_utils.rb#9
TailwindMerge::ClassGroupUtils::ARBITRARY_PROPERTY_REGEX = T.let(T.unsafe(nil), Regexp)

# source://tailwind_merge//lib/tailwind_merge/class_group_utils.rb#7
TailwindMerge::ClassGroupUtils::CLASS_PART_SEPARATOR = T.let(T.unsafe(nil), String)

# source://tailwind_merge//lib/tailwind_merge/config.rb#6
module TailwindMerge::Config
  include ::TailwindMerge::Validators

  # source://tailwind_merge//lib/tailwind_merge/config.rb#2267
  def merge_config(incoming_config); end
end

# source://tailwind_merge//lib/tailwind_merge/config.rb#159
TailwindMerge::Config::DEFAULTS = T.let(T.unsafe(nil), Hash)

# source://tailwind_merge//lib/tailwind_merge/config.rb#85
TailwindMerge::Config::SCALE_ALIGN_PRIMARY_AXIS = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/config.rb#86
TailwindMerge::Config::SCALE_ALIGN_SECONDARY_AXIS = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/config.rb#106
TailwindMerge::Config::SCALE_BG_POSITION = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/config.rb#107
TailwindMerge::Config::SCALE_BG_REPEAT = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/config.rb#108
TailwindMerge::Config::SCALE_BG_SIZE = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/config.rb#123
TailwindMerge::Config::SCALE_BLEND_MODE = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/config.rb#144
TailwindMerge::Config::SCALE_BLUR = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/config.rb#121
TailwindMerge::Config::SCALE_BORDER_WIDTH = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/config.rb#38
TailwindMerge::Config::SCALE_BREAK = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/config.rb#105
TailwindMerge::Config::SCALE_COLOR = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/config.rb#109
TailwindMerge::Config::SCALE_GRADIENT_STOP_POSITION = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/config.rb#84
TailwindMerge::Config::SCALE_GRID_AUTO_COLS_ROWS = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/config.rb#74
TailwindMerge::Config::SCALE_GRID_COL_ROW_START_AND_END = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/config.rb#83
TailwindMerge::Config::SCALE_GRID_COL_ROW_START_OR_END = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/config.rb#73
TailwindMerge::Config::SCALE_GRID_TEMPLATE_COLS_ROWS = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/config.rb#64
TailwindMerge::Config::SCALE_INSET = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/config.rb#122
TailwindMerge::Config::SCALE_LINE_STYLE = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/config.rb#87
TailwindMerge::Config::SCALE_MARGIN = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/config.rb#143
TailwindMerge::Config::SCALE_MASK_IMAGE_POSITION = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/config.rb#61
TailwindMerge::Config::SCALE_OVERFLOW = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/config.rb#62
TailwindMerge::Config::SCALE_OVERSCROLL = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/config.rb#39
TailwindMerge::Config::SCALE_POSITION = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/config.rb#60
TailwindMerge::Config::SCALE_POSITION_WITH_ARBITRARY = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/config.rb#110
TailwindMerge::Config::SCALE_RADIUS = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/config.rb#154
TailwindMerge::Config::SCALE_ROTATE = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/config.rb#155
TailwindMerge::Config::SCALE_SCALE = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/config.rb#88
TailwindMerge::Config::SCALE_SIZING = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/config.rb#156
TailwindMerge::Config::SCALE_SKEW = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/config.rb#157
TailwindMerge::Config::SCALE_TRANSLATE = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/config.rb#63
TailwindMerge::Config::SCALE_UNAMBIGUOUS_SPACING = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/config.rb#31
TailwindMerge::Config::THEME_ANIMATE = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/config.rb#31
TailwindMerge::Config::THEME_ASPECT = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/config.rb#31
TailwindMerge::Config::THEME_BLUR = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/config.rb#31
TailwindMerge::Config::THEME_BREAKPOINT = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/config.rb#31
TailwindMerge::Config::THEME_COLOR = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/config.rb#31
TailwindMerge::Config::THEME_CONTAINER = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/config.rb#31
TailwindMerge::Config::THEME_DROP_SHADOW = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/config.rb#31
TailwindMerge::Config::THEME_EASE = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/config.rb#31
TailwindMerge::Config::THEME_FONT = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/config.rb#31
TailwindMerge::Config::THEME_FONT_WEIGHT = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/config.rb#31
TailwindMerge::Config::THEME_INSET_SHADOW = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/config.rb#9
TailwindMerge::Config::THEME_KEYS = T.let(T.unsafe(nil), Array)

# source://tailwind_merge//lib/tailwind_merge/config.rb#31
TailwindMerge::Config::THEME_LEADING = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/config.rb#31
TailwindMerge::Config::THEME_PERSPECTIVE = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/config.rb#31
TailwindMerge::Config::THEME_RADIUS = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/config.rb#31
TailwindMerge::Config::THEME_SHADOW = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/config.rb#31
TailwindMerge::Config::THEME_SPACING = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/config.rb#31
TailwindMerge::Config::THEME_TEXT = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/config.rb#31
TailwindMerge::Config::THEME_TEXT_SHADOW = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/config.rb#31
TailwindMerge::Config::THEME_TRACKING = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/config.rb#36
TailwindMerge::Config::VALID_THEME_IDS = T.let(T.unsafe(nil), Set)

# source://tailwind_merge//lib/tailwind_merge.rb#16
class TailwindMerge::Merger
  include ::TailwindMerge::Validators
  include ::TailwindMerge::Config
  include ::TailwindMerge::ParseClassName
  include ::TailwindMerge::SortModifiers

  # @return [Merger] a new instance of Merger
  #
  # source://tailwind_merge//lib/tailwind_merge.rb#23
  def initialize(config: T.unsafe(nil)); end

  # source://tailwind_merge//lib/tailwind_merge.rb#30
  def merge(classes); end

  private

  # source://tailwind_merge//lib/tailwind_merge.rb#38
  def merge_class_list(class_list); end
end

# source://tailwind_merge//lib/tailwind_merge.rb#21
TailwindMerge::Merger::SPLIT_CLASSES_REGEX = T.let(T.unsafe(nil), Regexp)

# source://tailwind_merge//lib/tailwind_merge/parse_class_name.rb#7
module TailwindMerge::ParseClassName
  # Parse class name into parts.
  #
  # Inspired by `splitAtTopLevelOnly` used in Tailwind CSS
  #
  # @see https://github.com/tailwindlabs/tailwindcss/blob/v3.2.2/src/util/splitAtTopLevelOnly.js
  #
  # source://tailwind_merge//lib/tailwind_merge/parse_class_name.rb#17
  def parse_class_name(class_name, prefix: T.unsafe(nil)); end

  # source://tailwind_merge//lib/tailwind_merge/parse_class_name.rb#75
  def strip_important_modifier(base_class_name); end
end

# source://tailwind_merge//lib/tailwind_merge/parse_class_name.rb#8
TailwindMerge::ParseClassName::IMPORTANT_MODIFIER = T.let(T.unsafe(nil), String)

# source://tailwind_merge//lib/tailwind_merge/parse_class_name.rb#9
TailwindMerge::ParseClassName::MODIFIER_SEPARATOR = T.let(T.unsafe(nil), String)

# source://tailwind_merge//lib/tailwind_merge/parse_class_name.rb#10
TailwindMerge::ParseClassName::MODIFIER_SEPARATOR_LENGTH = T.let(T.unsafe(nil), Integer)

# source://tailwind_merge//lib/tailwind_merge/sort_modifiers.rb#4
module TailwindMerge::SortModifiers
  # Sorts modifiers according to following schema:
  # - Predefined modifiers are sorted alphabetically
  # - When an arbitrary variant appears, it must be preserved which modifiers are before and after it
  #
  # source://tailwind_merge//lib/tailwind_merge/sort_modifiers.rb#8
  def sort_modifiers(modifiers, order_sensitive_modifiers); end
end

# source://tailwind_merge//lib/tailwind_merge/parse_class_name.rb#4
class TailwindMerge::TailwindClass < ::Struct; end

# source://tailwind_merge//lib/tailwind_merge/version.rb#4
TailwindMerge::VERSION = T.let(T.unsafe(nil), String)

# source://tailwind_merge//lib/tailwind_merge/validators.rb#6
module TailwindMerge::Validators
  class << self
    # @return [Boolean]
    #
    # source://tailwind_merge//lib/tailwind_merge/validators.rb#8
    def arbitrary_value?(class_part, test_label, test_value); end

    # @return [Boolean]
    #
    # source://tailwind_merge//lib/tailwind_merge/validators.rb#17
    def arbitrary_variable?(class_part, test_label, should_match_no_label: T.unsafe(nil)); end

    # @return [Boolean]
    #
    # source://tailwind_merge//lib/tailwind_merge/validators.rb#30
    def integer?(x); end

    # @return [Boolean]
    #
    # source://tailwind_merge//lib/tailwind_merge/validators.rb#26
    def numeric?(x); end
  end
end

# source://tailwind_merge//lib/tailwind_merge/validators.rb#35
TailwindMerge::Validators::ARBITRARY_VALUE_REGEX = T.let(T.unsafe(nil), Regexp)

# source://tailwind_merge//lib/tailwind_merge/validators.rb#36
TailwindMerge::Validators::ARBITRARY_VARIABLE_REGEX = T.let(T.unsafe(nil), Regexp)

# source://tailwind_merge//lib/tailwind_merge/validators.rb#40
TailwindMerge::Validators::COLOR_FUNCTION_REGEX = T.let(T.unsafe(nil), Regexp)

# source://tailwind_merge//lib/tailwind_merge/validators.rb#37
TailwindMerge::Validators::FRACTION_REGEX = T.let(T.unsafe(nil), Regexp)

# source://tailwind_merge//lib/tailwind_merge/validators.rb#44
TailwindMerge::Validators::IMAGE_REGEX = T.let(T.unsafe(nil), Regexp)

# source://tailwind_merge//lib/tailwind_merge/validators.rb#66
TailwindMerge::Validators::IS_ANY = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/validators.rb#85
TailwindMerge::Validators::IS_ANY_NON_ARBITRARY = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/validators.rb#109
TailwindMerge::Validators::IS_ARBITRARY_IMAGE = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/validators.rb#97
TailwindMerge::Validators::IS_ARBITRARY_LENGTH = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/validators.rb#101
TailwindMerge::Validators::IS_ARBITRARY_NUMBER = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/validators.rb#105
TailwindMerge::Validators::IS_ARBITRARY_POSITION = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/validators.rb#113
TailwindMerge::Validators::IS_ARBITRARY_SHADOW = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/validators.rb#89
TailwindMerge::Validators::IS_ARBITRARY_SIZE = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/validators.rb#93
TailwindMerge::Validators::IS_ARBITRARY_VALUE = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/validators.rb#117
TailwindMerge::Validators::IS_ARBITRARY_VARIABLE = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/validators.rb#125
TailwindMerge::Validators::IS_ARBITRARY_VARIABLE_FAMILY_NAME = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/validators.rb#137
TailwindMerge::Validators::IS_ARBITRARY_VARIABLE_IMAGE = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/validators.rb#121
TailwindMerge::Validators::IS_ARBITRARY_VARIABLE_LENGTH = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/validators.rb#129
TailwindMerge::Validators::IS_ARBITRARY_VARIABLE_POSITION = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/validators.rb#141
TailwindMerge::Validators::IS_ARBITRARY_VARIABLE_SHADOW = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/validators.rb#133
TailwindMerge::Validators::IS_ARBITRARY_VARIABLE_SIZE = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/validators.rb#46
TailwindMerge::Validators::IS_FRACTION = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/validators.rb#81
TailwindMerge::Validators::IS_IMAGE = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/validators.rb#54
TailwindMerge::Validators::IS_INTEGER = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/validators.rb#169
TailwindMerge::Validators::IS_LABEL_FAMILY_NAME = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/validators.rb#153
TailwindMerge::Validators::IS_LABEL_IMAGE = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/validators.rb#161
TailwindMerge::Validators::IS_LABEL_LENGTH = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/validators.rb#165
TailwindMerge::Validators::IS_LABEL_NUMBER = T.let(T.unsafe(nil), Proc)

# Labels
#
# source://tailwind_merge//lib/tailwind_merge/validators.rb#149
TailwindMerge::Validators::IS_LABEL_POSITION = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/validators.rb#173
TailwindMerge::Validators::IS_LABEL_SHADOW = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/validators.rb#157
TailwindMerge::Validators::IS_LABEL_SIZE = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/validators.rb#68
TailwindMerge::Validators::IS_LENGTH_ONLY = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/validators.rb#75
TailwindMerge::Validators::IS_NEVER = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/validators.rb#50
TailwindMerge::Validators::IS_NUMBER = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/validators.rb#58
TailwindMerge::Validators::IS_PERCENT = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/validators.rb#77
TailwindMerge::Validators::IS_SHADOW = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/validators.rb#62
TailwindMerge::Validators::IS_TSHIRT_SIZE = T.let(T.unsafe(nil), Proc)

# source://tailwind_merge//lib/tailwind_merge/validators.rb#39
TailwindMerge::Validators::LENGTH_UNIT_REGEX = T.let(T.unsafe(nil), Regexp)

# Shadow always begins with x and y offset separated by underscore optionally prepended by inset
#
# source://tailwind_merge//lib/tailwind_merge/validators.rb#43
TailwindMerge::Validators::SHADOW_REGEX = T.let(T.unsafe(nil), Regexp)

# source://tailwind_merge//lib/tailwind_merge/validators.rb#38
TailwindMerge::Validators::TSHIRT_UNIT_REGEX = T.let(T.unsafe(nil), Regexp)
